### PR TITLE
update targetFramework to what csproj references

### PR DESCRIPTION
**Pull request by bryanrengo**

### CODE REVIEW

**Comment by f2prateek** [comment]
Thanks! This would resolve #52?

**Comment by bryanrengo** [comment]
It will, I was able to test this locally.

Caveat, this will not work for anything that targets net35 (or other netXX versions).

**Comment by f2prateek** [comment]
Gotcha. Would there be a way to support both?

**Comment by bryanrengo** [comment]
I spent the better part of yesterday afternoon trying different paths.  I'm sure there is, but at the moment I'm not sure how much time I have.

**Comment by f2prateek** [comment]
> Edit: Appears that .NET 3.5 assemblies cannot reference .NET Standard assemblies:

> https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-platforms-support

That's too bad :(

> You'd probably be able to get .NET 4.6 working though.

Would you happen to know what's involved in this? We can drop .NET 3.5 support, but would need to give existing customers the option to upgrade to a newer version rather than completely shutting it off.

**Comment by f2prateek** [comment]
This should not be required anymore.

**Pull request closed without merging**
